version: '3'
services:
  web:
    build:
      context: ./app
    ports:
      - "8080:5000"
    networks:
      - frontend
    depends_on:
      - redis-db
    environment:
      - REDIS_HOST=redis-db
      - REDIS_PORT=6379
  redis-db:
    image: redis
    ports:
      - "16379:6379"
    networks:
      - frontend
    volumes:
      - redis_data:/data
networks:
  frontend:
volumes:
  redis_data:
