---
deploy:
  dt01:
    stage: 'DeployStage01'
    environment: 'dev'
    subEnvironment: 'develop-01'
    datacenter: 'datacenter1'
    portNumber: 12333
  dt02:
    stage: 'DeployStage02'
    environment: 'dev'
    subEnvironment: 'develop-02'
    datacenter: 'datacenter2'
    portNumber: 12334
---
namespace:
  datacenter1:
    dev:
      api-001: 'cluster1.api1-dev.net'
      api-002: 'cluster1.api2-dev.net'
      api-003: 'cluster1.api3-dev.net'
      api-004: 'cluster1.api4-dev.net'
    regression:
      api-001: 'cluster1.api1-test.net'
      api-002: 'cluster1.api1-test.net'
      api-003: 'cluster1.api1-test.net'
      api-004: 'cluster1.api1-test.net'
  datacenter2:
    dev:
      api-001: 'cluster2.api1-dev.net'
      api-002: 'cluster2.api2-dev.net'
      api-003: 'cluster2.api3-dev.net'
      api-004: 'cluster2.api4-dev.net'
    regression:
      api-001: 'cluster2.api1-test.net'
      api-002: 'cluster2.api2-test.net'
      api-003: 'cluster2.api3-test.net'
      api-004: 'cluster2.api4-test.net'
---
podnamespace:
  dev:
    api-001: 'api1-dev'
    api-002: 'api2-dev'
    api-003: 'api3-dev'
    api-004: 'api4-dev'
  regression:
    api-001: 'api1-tst'
    api-002: 'api2-tst'
    api-003: 'api3-tst'
    api-004: 'api4-tst'
...
